#frase=input("INGRESE UNA FRASE POR FAVOR: ")
#print("Numero de palabras: " + str(len(frase.split(" "))))
f=open("frasepr.txt","w")
f.write('Esto es una prueba\n')
f.close()
f=open("frasepr.txt")
f.read()
s=f.read()
print("Numero de palabras: " + str(len(s.split(" "))))
